#spring:
#  application:
#    name: ecommerce
#  datasource:
#    url: jdbc:mysql://localhost:3306/billing_app
#    username: root
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#server:
#  servlet:
#    context-path: /api/v1.0
#  port: 8080


spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/billing_app
    password: admin
    username: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /api/v1.0

