spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/billing_app
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api/v1
